package me.gjwo.gedcom.pages.elements;

public enum ElementTypes {PAGE_HEADER, PERSON_LINK_ELEMENT, PARENTS_ELEMENT, FAMILIES_ELEMENT, COUPLE_TABLE_ELEMEMT, CENSUS_TABLE_ELEMENT, PERSON_KEY_EVENTS_ELEMENT
}
