package me.gjwo.gedcom.pages.elements;

public enum ElementTypes {
    PAGE_HEADER,
    PERSON_LINK_ELEMENT,
    PARENTS_ELEMENT,
    FAMILIES_ELEMENT,
    CENSUS_TABLE_ELEMENT,
    PERSON_KEY_EVENTS_ELEMENT,
    PERSON_ATTRIBUTES_ELEMENT,
    PERSON_FACTS_SUMMARY_ELEMENT,
    TEST_ELEMENT;
}
